version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          update_type: "all"
    ignored_updates:
      - match:
          dependency_name: "webpack"
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "weekly"
