name: Cargo Check
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --deny=warnings
      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: check
